apiVersion: v2
appVersion: latest
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 1.x.x
description: A Helm chart for karmada
kubeVersion: '>= 1.16.0-0'
maintainers:
- email: jrkeen@hotmail.com
  name: jrkeen
- email: jackson.cloudnative@gmail.com
  name: pidb
- email: shentiecheng@huawei.com
  name: Poor12
name: karmada
type: application
version: v1.9.0
