apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
    name: nginx-route
    labels:
        # This enables linkerd-failover to auto-adjust weights
        failover.linkerd.io/controlled-by: linkerd-failover
    annotations:
        # This can be used to designate the first service to route to
        failover.linkerd.io/primary-service: nginx
spec:
    service: nginx
    backends:
        - service: nginx
          weight: 1
        - service: nginx-desktop
          weight: 0